# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 362d13e6b9e1da75767063b2c966eea694fe5f723ed87786705097854e4a43bffc0bc30a65e67434e94b39106b74beda50e36e02d617f24c81400254972e6e6f

test:
  secret_key_base: 55d2f1a502e5190e4347683b6f8791c5117de9baa004214003dc474c10ef93a0726580fd5f2e433994d54b1a128706711f6b8bd82ff64ac6d4bcabcd970d14f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
